graph TD;

A{{Load page}}-->B{Initialized?}
B{Initialized?}--No-->D[Initialize with input data]-->F[Store inputs]
B{Initialized?}--Yes-->I[Get data from data store]-->F[Store inputs]
G{{User modified model parameters}}-->F[Save inputs in data store]
F[Store inputs]-->E[Generate graph]
E[Generate graph]-->J((Render HTML))
